name: Verify paper revision

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/verify-paper-revision.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile paper-revision.tex
        uses: xu-cheng/latex-action@v4
        with:
          root_file: paper-revision.tex
          compiler: pdflatex
          args: -file-line-error -halt-on-error -interaction=nonstopmode
